import { Student } from './student';

export const STUDENTS: Student[] = [
    { id: 1, name: 'Chris Thao', company: 'Pending', position: 'Pending'},
  { id: 1, name: 'Franklyn Reyes Varela', company: 'Ally', position: 'Software Test Engineer'},
  { id: 1, name: 'Hajar Alhassan', company: 'Wells Fargo', position: 'Systems Operation Analyst'},
  { id: 1, name: 'Laura Aleman', company: "Lowe's", position: 'Cyber'},
  { id: 1, name: 'Markus Harrison', company: "Lowe's", position: 'Cyber'},
  { id: 2, name: 'Anubhuti Shivhare', company: "Wells Fargo", position: 'Developer'},
  { id: 2, name: 'Erin Woodard', company: "Bank of America", position: 'Developer'},
  { id: 2, name: 'Geterry Sidbury-Crawford', company: "Pending", position: 'Developer'},
  { id: 2, name: 'Jharna Whitehurst', company: "Ally", position: 'Java Developer '},
  { id: 2, name: 'Julian Grant', company: "US Bank", position: 'Product Manager '},
  { id: 3, name: 'Damini Patel', company: "Ally", position: 'Big Data, AWS Snowflake Developer'},
  { id: 3, name: 'David Welles', company: "Ally", position: 'Technology Analyst '},
  { id: 3, name: 'Diana Flores', company: "Truist", position: 'Developer'},
  { id: 3, name: 'Kate Mejaski', company: "Pending", position: 'Developer'},
  { id: 3, name: 'Lydia Oshunkentan', company: "Lowe's", position: 'Cyber'},
  { id: 3, name: 'Shanta Dutta', company: "Ally", position: 'Technology'},
  { id: 4, name: 'April Craig', company: "US Bank", position: 'Developer'},
  { id: 4, name: "J'Sonya Watkins", company: "Truist", position: 'Associate Design Engineer'},
  { id: 4, name: 'Kaleb Hill', company: "Barings", position: 'Test Automation Engineer'},
  { id: 4, name: 'Lee Denis', company: "US Bank", position: 'Data Scientist '},
  { id: 4, name: 'Phillip Revak', company: "Bank of America", position: 'Developer'},
  { id: 5, name: 'Brice Lewis', company: "Pending", position: 'Pending'},
  { id: 5, name: 'Echu Seifu', company: "Bank of America", position: 'Developer'},
  { id: 5, name: 'Shweta Deshmukh', company: "Wells Fargo", position: 'Wholesale Capital Markets'},
  { id: 5, name: 'Sravanthi Rajavaram', company: "Ally", position: 'Fullstack/Java Developer'},
  { id: 5, name: 'Victor Vo', company: "Ally", position: 'DevOps Engineer'},
  { id: 6, name: 'Ibtxhis Khang', company: "Barings", position: 'UX/UI Designer'},
  { id: 6, name: 'Isaac Mendez', company: "US Bank", position: 'Product Manager'},
  { id: 6, name: 'Marcus Harris', company: "Coca-Cola", position: 'Developer'},
  { id: 6, name: 'Marquis Blocker', company: "Ally", position: 'Tech Analysis'},
  { id: 6, name: 'Wiynter Rodriguez', company: "Ally", position: 'API Developer'},
  { id: 7, name: 'Deepshikha Sharma', company: "Bank of America", position: 'Developer'},
  { id: 7, name: 'Jonathan Christopher', company: "Bank of America", position: 'Developer'},
  { id: 7, name: 'Lennart Bendfeldt', company: "Ally", position: 'Assoc Developer -- Software Dev'},
  { id: 7, name: 'Nicholas Harrison', company: "Lowe's", position: 'Cyber'},
  { id: 7, name: 'Sophie Cam', company: "Lowe's", position: 'Cyber'},
];